# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=150)),
                ('desciption', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('atc', models.CharField(max_length=1)),
            ],
        ),
    ]
