# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=80)),
                ('address', models.TextField(max_length=150)),
            ],
        ),
    ]
