# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-14 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_desciption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desciption',
            field=models.TextField(default='Description Here'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Location here', max_length=120),
        ),
    ]
